
<!-- end content -->
</tr>
</td>

</table>

</td>
</tr>
</table>

<!-- footer table -->

<table width="100%" cellpadding="0" cellspacing="0" border="0" align="center" bgcolor="#66CCFF">

<tr>
<td width="100%" align="center">
   <p><font size=1>
   News items are the property of their posters. 
   All the rest &copy; 1999, 2001 - 2003 by Free Software Foundation, Inc.,
   59 Temple Place - Suite 330, Boston, MA 02111, USA <br>

   Verbatim copying and distribution of this entire article is permitted in any 
   medium, provided this notice is preserved
   </font></p>
</td>
</tr>

</table>

&nbsp; 

</body>

</html>