<h3>New Releases of GNUe Tools (0.5.3)</h3>

<p>5 March 2004</p>
<p>
The GNU Enterprise team is proud to announce a new release of
it's enterprise application development suite.  This release
includes:
<ul>
    <li> GNUe Forms 0.5.3
    <li> GNUe Reports 0.1.4
    <li> GNUe Designer 0.5.3
    <li> GNUe AppServer 0.0.6
    <li> GNUe Common 0.5.3
</ul>

</p>

<p><a href="../news/news137.html">More ...</a></p>
