<h3>GNUe Tools 0.4.3 setup.exe for Microsoft Windows</h3>

<p>16th December 2002</p>
<p>The 0.4.3 release of Forms, Designer and Common and the 
0.1.0 release of Reports are now available
as a single setup.exe for Microsoft Windows, 
including many of the supported database drivers. This
is available in two versions - one with the python 
console window visible (to aid debugging) and one with 
it switched off. They can be downloaded from the website
<a href="http://www.gnuenterprise.org/downloads/current.php">here</a>.</p>

<p><a href="../news/news124.html">More ...</a></p>
