<h3>New Releases of GNUe Tools (0.5.2)</h3>

<p>24 October 2003</p>
<p>
The GNU Enterprise team is proud to announce a new release of
it's enterprise application development suite.  This release
includes:
<ul>
    <li> GNUe Forms 0.5.2
    <li> GNUe Reports 0.1.3
    <li> GNUe Designer 0.5.2
    <li> GNUe Navigator 0.0.6
    <li> GNUe AppServer 0.0.5
    <li> GNUe Common 0.5.2
</ul>

</p>

<p><a href="../news/news136.html">More ...</a></p>
