<h3>Web site changes</h3>

<p>05 February 2003</p>
<p>The few visible recent changes to the website (plus 
the occasional glitch) mask a lot more changes underneath. 
The most significant change is that the site is now
available, in the same format, at both
<a href="http://www.gnu.org/software/gnue/project/what.html">
www.gnu.org/software/gnue/</a> and
<a href="http://www.gnuenterprise.org/project/what.html">
www.gnuenterprise.org</a>.</p>

<p><a href="../news/news129.html">More ...</a></p>
