<h3>New release of tools (0.5.0 series)</h3>

<p>30 April 2003</p>
<p>
The GNU Enterprise team is proud to announce a new release of
it's enterprise application development suite.  This major
release includes:
<ul>
    <li> GNUe Forms 0.5.0
    <li> GNUe Reports 0.1.1
    <li> GNUe Designer 0.5.0
    <li> GNUe Navigator 0.0.4
    <li> GNUe AppServer 0.0.3
    <li> GNUe Common 0.5.0
</ul>
</p>

<p><a href="../news/news134.html">More ...</a></p>
